V\ValoraBundle\Entity\TbTipoPersona:
    type: entity
    table: tb_Tipo_Persona
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        vdescripcion:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            column: vDescripcion
    lifecycleCallbacks: {  }
