B\BuffaloBundle\Entity\TbCompra:
    type: entity
    table: tb_Compra
    indexes:
        fk_tb_Compra_Persona:
            columns:
                - fk_iID_PERSONA
        fk_tb_Mesa:
            columns:
                - fk_iID_MESA
        fk_tb_Compra_Persona2:
            columns:
                - fk_iID_MESERO
        fk_tb_Compra_1:
            columns:
                - fk_iID_ESTADO_COMPRA
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dtfechaCompra:
            type: datetime
            nullable: false
            comment: ''
            column: dtFECHA_COMPRA
        dcosto:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: dCOSTO
    manyToOne:
        fkIidPersona:
            targetEntity: TbPersona
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_iID_PERSONA:
                    referencedColumnName: id
            orphanRemoval: false
        fkIidMesa:
            targetEntity: TbMesa
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_iID_MESA:
                    referencedColumnName: id
            orphanRemoval: false
        fkIidEstadoCompra:
            targetEntity: TbEstadoCompra
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_iID_ESTADO_COMPRA:
                    referencedColumnName: id
            orphanRemoval: false
        fkIidMesero:
            targetEntity: TbPersona
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_iID_MESERO:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
