B\BuffaloBundle\Entity\TbEstadoPersona:
    type: entity
    table: tb_ESTADO_PERSONA
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        vdescripcion:
            type: string
            nullable: true
            length: 150
            fixed: false
            comment: ''
            default: 'Solicitud Registro'
            column: vDescripcion
    lifecycleCallbacks: {  }
