B\BuffaloBundle\Entity\TbIngrediente:
    type: entity
    table: tb_Ingrediente
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        vnombre:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            column: vNOMBRE
        icantidad:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: iCANTIDAD
        dcosto:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: dCOSTO
        dprecio:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: dPRECIO
        vestado:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            column: vESTADO
    lifecycleCallbacks: {  }
