B\BuffaloBundle\Entity\TbIngrediente:
    type: entity
    table: tb_Ingrediente
    indexes:
        fk_iID_ESTADO_ING:
            columns:
                - fk_iID_ESTADO_ING
        fk_iID_MEDIDA_ING:
            columns:
                - fk_iID_MEDIDA_ING
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        vnombre:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            column: vNOMBRE
        icantidad:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: iCANTIDAD
        dcosto:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: dCOSTO
    manyToOne:
        fkIidEstadoIng:
            targetEntity: TbEstadoIng
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_iID_ESTADO_ING:
                    referencedColumnName: id
            orphanRemoval: false
        fkIidMedidaIng:
            targetEntity: TbMedida
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_iID_MEDIDA_ING:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
