B\BuffaloBundle\Entity\TbMesa:
    type: entity
    table: tb_Mesa
    indexes:
        fk_iID_ESTADO_MESA:
            columns:
                - fk_iID_ESTADO_MESA
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        inroMesa:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: iNRO_MESA
        destatus:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            column: dESTATUS
    manyToOne:
        fkIidEstadoMesa:
            targetEntity: TbEstadoMesa
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_iID_ESTADO_MESA:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
