B\BuffaloBundle\Entity\TbMedida:
    type: entity
    table: tb_Medida
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        vnombre:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            column: vNOMBRE
    lifecycleCallbacks: {  }
