B\BuffaloBundle\Entity\TbPlato:
    type: entity
    table: tb_Plato
    indexes:
        fk_iID_ESTADO:
            columns:
                - fk_iID_ESTADO
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        vnombre:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            column: vNOMBRE
        dprecio:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: dPRECIO
    manyToOne:
        fkIidEstado:
            targetEntity: TbEstadoPlato
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_iID_ESTADO:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
