Paquete:
    path:     /
    defaults: { _controller: "VValoraBundle:TbPaquete:index" }

Paquete_show:
    path:     /{id}/show
    defaults: { _controller: "VValoraBundle:TbPaquete:show" }

Paquete_new:
    path:     /new
    defaults: { _controller: "VValoraBundle:TbPaquete:new" }

Paquete_create:
    path:     /create
    defaults: { _controller: "VValoraBundle:TbPaquete:create" }
    requirements: { _method: post }

Paquete_edit:
    path:     /{id}/edit
    defaults: { _controller: "VValoraBundle:TbPaquete:edit" }

Paquete_update:
    path:     /{id}/update
    defaults: { _controller: "VValoraBundle:TbPaquete:update" }
    requirements: { _method: post|put }

Paquete_delete:
    path:     /{id}/delete
    defaults: { _controller: "VValoraBundle:TbPaquete:delete" }
    requirements: { _method: post|delete }
