v_valora:
    resource: "@VValoraBundle/Resources/config/routing.yml"
    prefix:   /


VValoraBundle_homepage:
    pattern:  /
    defaults: { _controller: VValoraBundle:Default:index}
    requirements:
        _method:  GET

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

login:
    pattern:   /login
    defaults:  { _controller: VValoraBundle:Default:login }
login_check:
    pattern:   /login_check




