security:
    access_denied_url: /erroracceso  
    encoders:
        B\BuffaloBundle\Entity\TbPersona: sha512

    role_hierarchy:
        ROLE_USER:  ROLE_USER
        ROLE_ADMIN: ROLE_ADMIN
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: B\BuffaloBundle\Entity\TbPersona, property: icedula} 
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern:    ^/
            form_login: 
                default_target_path: /index
                provider: main
                check_path: /login_check
                login_path: /login
                always_use_default_target_path: true
            logout:
                path: /logout
                target: /index
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
