parameters:
#    b_buffalo.example.class: B\BuffaloBundle\Example

services:
#    b_buffalo.example:
#        class: %b_buffalo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
