parameters:
#    b_buffalo.example.class: B\BuffaloBundle\Example

services:
#    b_buffalo.example:
#        class: %b_buffalo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
     b.buffalo.admin.user:
         class: B\BuffaloBundle\Admin\UserAdmin
         tags:
             - { name: sonata.admin, manager_type: orm, group: T, label: Users }
         arguments: [null, B\BuffaloBundle\Entity\User, BBuffaloBundle:UserAdmin]
