v_valora_homepage:
    path:     /index
    defaults: { _controller: VValoraBundle:Default:index }

index:
    path:    /index 
    defaults: { _controller: VValoraBundle:Default:index }


erroracceso:
    pattern:  /erroracceso
    defaults: { _controller: VValoraBundle:Default:erroracceso }

logout:
     pattern: /logout

forgotpass:
    pattern:  /forgotpass
    defaults: { _controller: "VValoraBundle:Default:newforgot" }

createforgot:
    pattern:  /createforgot
    defaults: { _controller: "VValoraBundle:Default:createforgot" }
    requirements: { _method: post }

VValoraBundle_Persona:
    resource: "@VValoraBundle/Resources/config/routing/tbpersona.yml"
    prefix:   /Persona

VValoraBundle_TipoPersona:
    resource: "@VValoraBundle/Resources/config/routing/tbtipopersona.yml"
    prefix:   /TipoPersona

VValoraBundle_EdoServicio:
    resource: "@VValoraBundle/Resources/config/routing/tbedoservicio.yml"
    prefix:   /EdoServicio


VValoraBundle_Producto:
    resource: "@VValoraBundle/Resources/config/routing/tbproducto.yml"
    prefix:   /Producto

VValoraBundle_Paquete:
    resource: "@VValoraBundle/Resources/config/routing/tbpaquete.yml"
    prefix:   /Paquete

VValoraBundle_RelPaqueteProducto:
    resource: "@VValoraBundle/Resources/config/routing/tbrelpaqueteproducto.yml"
    prefix:   /RelPaqueteProducto

VValoraBundle_Servicio:
    resource: "@VValoraBundle/Resources/config/routing/tbservicio.yml"
    prefix:   /Servicio


