ens_edoCompra:
    path:     /
    defaults: { _controller: "BBuffaloBundle:TbEstadoCompra:index" }

ens_edoCompra_show:
    path:     /{id}/show
    defaults: { _controller: "BBuffaloBundle:TbEstadoCompra:show" }

ens_edoCompra_new:
    path:     /new
    defaults: { _controller: "BBuffaloBundle:TbEstadoCompra:new" }

ens_edoCompra_create:
    path:     /create
    defaults: { _controller: "BBuffaloBundle:TbEstadoCompra:create" }
    requirements: { _method: post }

ens_edoCompra_edit:
    path:     /{id}/edit
    defaults: { _controller: "BBuffaloBundle:TbEstadoCompra:edit" }

ens_edoCompra_update:
    path:     /{id}/update
    defaults: { _controller: "BBuffaloBundle:TbEstadoCompra:update" }
    requirements: { _method: post|put }

ens_edoCompra_delete:
    path:     /{id}/delete
    defaults: { _controller: "BBuffaloBundle:TbEstadoCompra:delete" }
    requirements: { _method: post|delete }
