ens_edoPersona:
    path:     /
    defaults: { _controller: "BBuffaloBundle:TbEstadoPersona:index" }

ens_edoPersona_show:
    path:     /{id}/show
    defaults: { _controller: "BBuffaloBundle:TbEstadoPersona:show" }

ens_edoPersona_new:
    path:     /new
    defaults: { _controller: "BBuffaloBundle:TbEstadoPersona:new" }

ens_edoPersona_create:
    path:     /create
    defaults: { _controller: "BBuffaloBundle:TbEstadoPersona:create" }
    requirements: { _method: post }

ens_edoPersona_edit:
    path:     /{id}/edit
    defaults: { _controller: "BBuffaloBundle:TbEstadoPersona:edit" }

ens_edoPersona_update:
    path:     /{id}/update
    defaults: { _controller: "BBuffaloBundle:TbEstadoPersona:update" }
    requirements: { _method: post|put }

ens_edoPersona_delete:
    path:     /{id}/delete
    defaults: { _controller: "BBuffaloBundle:TbEstadoPersona:delete" }
    requirements: { _method: post|delete }
