ens_ingredientes:
    path:     /
    defaults: { _controller: "BBuffaloBundle:TbIngrediente:index" }

ens_ingredientes_show:
    path:     /{id}/show
    defaults: { _controller: "BBuffaloBundle:TbIngrediente:show" }

ens_ingredientes_new:
    path:     /new
    defaults: { _controller: "BBuffaloBundle:TbIngrediente:new" }

ens_ingredientes_create:
    path:     /create
    defaults: { _controller: "BBuffaloBundle:TbIngrediente:create" }
    requirements: { _method: post }

ens_ingredientes_edit:
    path:     /{id}/edit
    defaults: { _controller: "BBuffaloBundle:TbIngrediente:edit" }

ens_ingredientes_update:
    path:     /{id}/update
    defaults: { _controller: "BBuffaloBundle:TbIngrediente:update" }
    requirements: { _method: post|put }

ens_ingredientes_delete:
    path:     /{id}/delete
    defaults: { _controller: "BBuffaloBundle:TbIngrediente:delete" }
    requirements: { _method: post|delete }
