ens_platos:
    path:     /
    defaults: { _controller: "BBuffaloBundle:TbPlato:index" }

ens_platos_show:
    path:     /{id}/show
    defaults: { _controller: "BBuffaloBundle:TbPlato:show" }

ens_platos_new:
    path:     /new
    defaults: { _controller: "BBuffaloBundle:TbPlato:new" }

ens_platos_create:
    path:     /create
    defaults: { _controller: "BBuffaloBundle:TbPlato:create" }
    requirements: { _method: post }

ens_platos_edit:
    path:     /{id}/edit
    defaults: { _controller: "BBuffaloBundle:TbPlato:edit" }

ens_platos_update:
    path:     /{id}/update
    defaults: { _controller: "BBuffaloBundle:TbPlato:update" }
    requirements: { _method: post|put }

ens_platos_delete:
    path:     /{id}/delete
    defaults: { _controller: "BBuffaloBundle:TbPlato:delete" }
    requirements: { _method: post|delete }
