ens_inventario:
    path:     /
    defaults: { _controller: "BBuffaloBundle:TbRelPlatoIngrediente:index" }

ens_inventario_show:
    path:     /{id}/show
    defaults: { _controller: "BBuffaloBundle:TbRelPlatoIngrediente:show" }

ens_inventario_new:
    path:     /new
    defaults: { _controller: "BBuffaloBundle:TbRelPlatoIngrediente:new" }

ens_inventario_create:
    path:     /create
    defaults: { _controller: "BBuffaloBundle:TbRelPlatoIngrediente:create" }
    requirements: { _method: post }

ens_inventario_edit:
    path:     /{id}/edit
    defaults: { _controller: "BBuffaloBundle:TbRelPlatoIngrediente:edit" }

ens_inventario_update:
    path:     /{id}/update
    defaults: { _controller: "BBuffaloBundle:TbRelPlatoIngrediente:update" }
    requirements: { _method: post|put }

ens_inventario_delete:
    path:     /{id}/delete
    defaults: { _controller: "BBuffaloBundle:TbRelPlatoIngrediente:delete" }
    requirements: { _method: post|delete }
