ens_pedidos:
    path:     /
    defaults: { _controller: "BBuffaloBundle:TbRelCompraPlato:index" }

ens_pedidos_show:
    path:     /{id}/show
    defaults: { _controller: "BBuffaloBundle:TbRelCompraPlato:show" }

ens_pedidos_new:
    path:     /new
    defaults: { _controller: "BBuffaloBundle:TbRelCompraPlato:new" }

ens_pedidos_create:
    path:     /create
    defaults: { _controller: "BBuffaloBundle:TbRelCompraPlato:create" }
    requirements: { _method: post }

ens_pedidos_edit:
    path:     /{id}/edit
    defaults: { _controller: "BBuffaloBundle:TbRelCompraPlato:edit" }

ens_pedidos_update:
    path:     /{id}/update
    defaults: { _controller: "BBuffaloBundle:TbRelCompraPlato:update" }
    requirements: { _method: post|put }

ens_pedidos_delete:
    path:     /{id}/delete
    defaults: { _controller: "BBuffaloBundle:TbRelCompraPlato:delete" }
    requirements: { _method: post|delete }
